### ISSUE TITLE
Error starting Metals server

### ISSUE THREAD

**Issue by mads-hartmann** [laughedelic/atom-ide-scala#60]
Hi,
I get the following error when I try to start the Metals server.

```stderr Error:
stderr   org.scalameta:metals_2.12:
stderr     not found: /Users/hartmann/.ivy2/local/org.scalameta/metals_2.12/ivys/ivy.xml
stderr     not found: https://repo1.maven.org/maven2/org/scalameta/metals_2.12//metals_2.12-.pom
stderr     not found: https://dl.bintray.com/scalameta/maven/org/scalameta/metals_2.12//metals_2.12-.pom
```

Any idea how best to debug this?

Cheers

**Comment by laughedelic** [comment]
Hi @mads-hartmann! I'm glad that you're trying it out 😊 

This is an error from coursier and it looks like the version is empty. I see now that I shipped 0.6.0 with the empty default version (because there's a `none` option) and didn't set it properly for Metals.

I'll fix this tomorrow, but meanwhile just open the [plugin settings](atom://settings-view/show-package?package=ide-scala) and set `Language server version` to `0.1.0-M1+90-fcac1cc3` (see published versions on [Bintray](https://bintray.com/scalameta/maven/metals)). Let me know how it works then.

**Comment by mads-hartmann** [comment]
@laughedelic Awesome, thanks :) I'll see if I can give it a go later today.

**Comment by mads-hartmann** [comment]
Setting the version explicitly works 👍 I get jump to declaration but I don't get code completions. I'll play around some more and open another issue if I can't resolve it :)

**Comment by laughedelic** [comment]
Completions are disabled by default. You can turn it on in the plugin settings (in the Metals/Presentation compiler section), but please, be aware that it's very unstable 🌵 See the [related docs](https://github.com/scalameta/metals/blob/master/docs/overview.md#fast-completions).

**Comment by mads-hartmann** [comment]
@laughedelic Ah sorry, should've read the docs more closely 👍 Thanks for working on this project it's super cool 🙏
