### ISSUE TITLE
Didn't worked until I manually installed "language-scala"

### ISSUE THREAD

**Issue by NicolaeNMV** [laughedelic/atom-ide-scala#75]
I was very confused about what to do to activate the plugin once it was installed.

It turned out I had to manually install language-scala even though in the documentation it says that it will installed automatically.

> On the first launch it will automatically install its dependencies if needed:

Anyway, hope this helps anyone else wondering why it doesn't work.

**Comment by laughedelic** [comment]
Hi @NicolaeNMV! Thanks for reporting it. I will update the readme. 

It was installed automatically before, but now it's not possible. The reason is that ide-scala package will activate only when you open a scala file and language-scala is used to determine that it's a scala file. Before ide-scala was activated unconditionally and it would add some time to Atom startup.
